In [55]:
import pandas as pd

## Importo il dataframe imdb_movies, scaricato da Kaggle

link alla pagina: https://www.kaggle.com/datasets/ashpalsingh1525/imdb-movies-dataset

#### Questo è il df principale per la nostra analisi. Contiene informazioni su `genere`, `cast`, `budget`, `revenue` e `score`

In [56]:
imdb_movies = pd.read_csv("C:\\Users\\loren\\Desktop\\Final Project\\imdb_movies.csv")

In [57]:
imdb_movies

,names,date_x,score,genre,overview,crew,orig_title,status,orig_lang,budget_x,revenue,country
0,Creed III,03/02/2023,73.0,"Drama, Action","After dominating the boxing world, Adonis Cree...","Michael B. Jordan, Adonis Creed, Tessa Thompso...",Creed III,Released,English,75000000.0,2.716167e+08,AU
1,Avatar: The Way of Water,12/15/2022,78.0,"Science Fiction, Adventure, Action",Set more than a decade after the events of the...,"Sam Worthington, Jake Sully, Zoe Saldaña, Neyt...",Avatar: The Way of Water,Released,English,460000000.0,2.316795e+09,AU
2,The Super Mario Bros. Movie,04/05/2023,76.0,"Animation, Adventure, Family, Fantasy, Comedy","While working underground to fix a water main,...","Chris Pratt, Mario (voice), Anya Taylor-Joy, P...",The Super Mario Bros. Movie,Released,English,100000000.0,7.244590e+08,AU
3,Mummies,01/05/2023,70.0,"Animation, Comedy, Family, Adventure, Fantasy","Through a series of unfortunate events, three ...","Óscar Barberán, Thut (voice), Ana Esther Albor...",Momias,Released,"Spanish, Castilian",12300000.0,3.420000e+07,AU
4,Supercell,03/17/2023,61.0,Action,Good-hearted teenager William always lived in ...,"Skeet Ulrich, Roy Cameron, Anne Heche, Dr Quin...",Supercell,Released,English,77000000.0,3.409420e+08,US
...,...,...,...,...,...,...,...,...,...,...,...,...
10173,20th Century Women,12/28/2016,73.0,Drama,"In 1979 Santa Barbara, California, Dorothea Fi...","Annette Bening, Dorothea Fields, Lucas Jade Zu...",20th Century Women,Released,English,7000000.0,9.353729e+06,US
10174,Delta Force 2: The Colombian Connection,08/24/1990,54.0,Action,When DEA agents are taken captive by a ruthles...,"Chuck Norris, Col. Scott McCoy, Billy Drago, R...",Delta Force 2: The Colombian Connection,Released,English,9145817.8,6.698361e+06,US
10175,The Russia House,12/21/1990,61.0,"Drama, Thriller, Romance","Barley Scott Blair, a Lisbon-based editor of R...","Sean Connery, Bartholomew 'Barley' Scott Blair...",The Russia House,Released,English,21800000.0,2.299799e+07,US
10176,Darkman II: The Return of Durant,07/11/1995,55.0,"Action, Adventure, Science Fiction, Thriller, ...",Darkman and Durant return and they hate each o...,"Larry Drake, Robert G. Durant, Arnold Vosloo, ...",Darkman II: The Return of Durant,Released,English,116000000.0,4.756613e+08,US
10177,The Swan Princess: A Royal Wedding,07/20/2020,70.0,"Animation, Family, Fantasy",Princess Odette and Prince Derek are going to ...,"Nina Herzog, Princess Odette (voice), Yuri Low...",The Swan Princess: A Royal Wedding,Released,English,92400000.0,5.394018e+08,GB

In [58]:
imdb_movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10178 entries, 0 to 10177
Data columns (total 12 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   names       10178 non-null  object
 1   date_x      10178 non-null  object
 2   score       10178 non-null  float64
 3   genre       10093 non-null  object
 4   overview    10178 non-null  object
 5   crew        10122 non-null  object
 6   orig_title  10178 non-null  object
 7   status      10178 non-null  object
 8   orig_lang   10178 non-null  object
 9   budget_x    10178 non-null  float64
 10  revenue     10178 non-null  float64
 11  country     10178 non-null  object
dtypes: float64(3), object(9)
memory usage: 954.3+ KB

In [59]:
imdb_movies_clean = imdb_movies.copy()

#### Ma questo df ha un problema: i film con lo stesso titolo non sono facilmente distinguibili, se non confrontando la data di uscita

In [60]:
imdb_movies_clean.loc[imdb_movies_clean['names'] == 'Pinocchio']

,names,date_x,score,genre,overview,crew,orig_title,status,orig_lang,budget_x,revenue,country
396,Pinocchio,09/08/2022,65.0,"Fantasy, Adventure, Family",A wooden puppet embarks on a thrilling adventu...,"Benjamin Evan Ainsworth, Pinocchio (voice), To...",Pinocchio,Released,English,45000000.0,31681811.0,AU
397,Pinocchio,09/08/2022,65.0,"Fantasy, Adventure, Family",A wooden puppet embarks on a thrilling adventu...,"Benjamin Evan Ainsworth, Pinocchio (voice), To...",Pinocchio,Released,English,13200000.0,30360375.0,AU
398,Pinocchio,09/08/2022,65.0,"Fantasy, Adventure, Family",A wooden puppet embarks on a thrilling adventu...,"Benjamin Evan Ainsworth, Pinocchio (voice), To...",Pinocchio,Released,English,2289247.0,84300000.0,AU
1078,Pinocchio,05/16/1940,71.0,"Animation, Family",Lonely toymaker Geppetto has his wishes answer...,"Dickie Jones, Pinocchio / Alexander (voice) (u...",Pinocchio,Released,English,45000000.0,31681811.0,AU
1079,Pinocchio,05/16/1940,71.0,"Animation, Family",Lonely toymaker Geppetto has his wishes answer...,"Dickie Jones, Pinocchio / Alexander (voice) (u...",Pinocchio,Released,English,13200000.0,30360375.0,AU
1080,Pinocchio,05/16/1940,71.0,"Animation, Family",Lonely toymaker Geppetto has his wishes answer...,"Dickie Jones, Pinocchio / Alexander (voice) (u...",Pinocchio,Released,English,2289247.0,84300000.0,AU
2777,Pinocchio,09/29/2020,66.0,"Drama, Family, Fantasy",In this live-action adaptation of the beloved ...,"Federico Ielapi, Pinocchio, Roberto Benigni, M...",Pinocchio,Released,Italian,45000000.0,31681811.0,AU
2778,Pinocchio,09/29/2020,66.0,"Drama, Family, Fantasy",In this live-action adaptation of the beloved ...,"Federico Ielapi, Pinocchio, Roberto Benigni, M...",Pinocchio,Released,Italian,13200000.0,30360375.0,AU
2779,Pinocchio,09/29/2020,66.0,"Drama, Family, Fantasy",In this live-action adaptation of the beloved ...,"Federico Ielapi, Pinocchio, Roberto Benigni, M...",Pinocchio,Released,Italian,2289247.0,84300000.0,AU
9543,Pinocchio,10/11/2002,58.0,"Comedy, Family, Fantasy",Roberto Benigni adapts the classic children's ...,"Roberto Benigni, Pinocchio, Nicoletta Braschi,...",Pinocchio,Released,Italian,45000000.0,31681811.0,IT
9544,Pinocchio,10/11/2002,58.0,"Comedy, Family, Fantasy",Roberto Benigni adapts the classic children's ...,"Roberto Benigni, Pinocchio, Nicoletta Braschi,...",Pinocchio,Released,Italian,13200000.0,30360375.0,IT
9545,Pinocchio,10/11/2002,58.0,"Comedy, Family, Fantasy",Roberto Benigni adapts the classic children's ...,"Roberto Benigni, Pinocchio, Nicoletta Braschi,...",Pinocchio,Released,Italian,2289247.0,84300000.0,IT

Ad esempio, se cerchiamo il film "Pinocchio" vediamo che esistono varie versioni di anni, genere e lingua diversi; e che in questi casi i dati di budget e fatturato non sono attendibili.


#### Occorre anzitutto identificare quali sono i duplicati e cosa è duplicato

In [61]:
# identifichiamo i duplicati
doppioni = imdb_movies_clean[imdb_movies_clean.duplicated(subset='names', keep=False)]
doppioni.sort_values(by=['names'])

,names,date_x,score,genre,overview,crew,orig_title,status,orig_lang,budget_x,revenue,country
2072,12 Angry Men,10/10/1957,85.0,Drama,The defense and the prosecution have rested an...,"Martin Balsam, Juror 1, John Fiedler, Juror 2,...",12 Angry Men,Released,English,340000.0,379.0,AU
9741,12 Angry Men,08/17/1997,77.0,"Crime, Drama, TV Movie",During the trial of a man accused of his fathe...,"Courtney B. Vance, Foreman, Ossie Davis, Juror...",12 Angry Men,Released,English,340000.0,379.0,US
7283,"20,000 Leagues Under the Sea",12/29/1955,71.0,"Adventure, Drama, Family, Fantasy, Science Fic...",A ship sent to investigate a wave of mysteriou...,"Kirk Douglas, Ned Land, James Mason, Captain N...","20,000 Leagues Under the Sea",Released,English,5000000.0,28200000.0,AU
7284,"20,000 Leagues Under the Sea",12/29/1955,71.0,"Adventure, Drama, Family, Fantasy, Science Fic...",A ship sent to investigate a wave of mysteriou...,"Kirk Douglas, Ned Land, James Mason, Captain N...","20,000 Leagues Under the Sea",Released,English,200000.0,8000000.0,AU
7213,A Christmas Carol,10/09/1984,74.0,"Drama, Fantasy, TV Movie, Family",A bitter old miser who makes excuses for his u...,"George C. Scott, Ebenezer Scrooge, Roger Rees,...",A Christmas Carol,Released,English,104200000.0,379238515.8,GB
...,...,...,...,...,...,...,...,...,...,...,...,...
826,Wrong Turn,02/04/2021,60.0,"Horror, Thriller",Jen and a group of friends set out to hike the...,"Charlotte Vega, Jennifer Shaw, Adain Bradley, ...",Wrong Turn,Released,English,10000000.0,28649556.0,AU
8858,Wuthering Heights,10/16/1992,67.0,"Drama, Romance",Young orphan Heathcliff is adopted by the weal...,"Juliette Binoche, Catherine Linton, Ralph Fien...",Wuthering Heights,Released,English,8000000.0,2721534.0,US
9749,Wuthering Heights,10/11/2012,59.0,"Drama, Romance","Yorkshire moorlands, northern England, in the ...","Kaya Scodelario, Older Cathy, James Howson, Ol...",Wuthering Heights,Released,English,8000000.0,2721534.0,AU
4326,X,11/23/2011,65.0,"Action, Thriller, Romance",A veteran call girl and a runaway prostitute w...,"Viva Bianca, Holly Rowe, Hanna Mangan Lawrence...",X,Released,English,1000000.0,15113105.0,AU
369,X,03/24/2022,68.0,"Horror, Mystery, Thriller","In 1979, a group of young filmmakers set out t...","Mia Goth, Maxine Minx / Pearl, Jenna Ortega, L...",X,Released,English,1000000.0,15113105.0,AU

- In alcuni casi si nota che i valori di budget e fatturato sono stati copiati per film omonimi (ad esempio "12 Angry Men")
- In altri casi lo stesso film ha due righe con valori monetari diversi (come "20,000 Leagues Under the Sea"). In entrambi i casi non abbiamo una entry attendibile.

In un primo passaggio identifico le righe che effettivamente si ripetono, controllando sia il nome, la data di uscita che la revenue.

In [62]:
doppioni = imdb_movies_clean[imdb_movies_clean.duplicated(subset=['names','date_x','revenue'], keep=False)]
doppioni

Empty DataFrame
Columns: [names, date_x, score, genre, overview, crew, orig_title, status, orig_lang, budget_x, revenue, country]
Index: []

In questo caso non ottengo nulla. Significa che non ci sono righe ripetute, quindi tutti i duplicati di nome e data avranno diversi fatturati.

#### Procedo allora eliminando **tutti** i film con lo stesso titolo e data, poiché non ho modo di verificare agilmente quali siano i valori di fatturato corretti quando ne ho diversi per lo stesso film.

In [63]:
doppioni = imdb_movies_clean[imdb_movies_clean.duplicated(subset=['names','date_x'], keep=False)]
doppioni

,names,date_x,score,genre,overview,crew,orig_title,status,orig_lang,budget_x,revenue,country
95,Scream,01/13/2022,67.0,"Horror, Mystery, Thriller",Twenty-five years after a streak of brutal mur...,"Melissa Barrera, Sam Carpenter, Mason Gooding,...",Scream,Released,English,24000000.0,1.388748e+08,AU
96,Scream,01/13/2022,67.0,"Horror, Mystery, Thriller",Twenty-five years after a streak of brutal mur...,"Melissa Barrera, Sam Carpenter, Mason Gooding,...",Scream,Released,English,15000000.0,1.730466e+08,AU
109,The Ten Commandments,12/12/1958,78.0,"Drama, History","Escaping death, a Hebrew infant is raised in a...","Charlton Heston, Moses, Yul Brynner, Rameses, ...",The Ten Commandments,Released,English,13500000.0,8.543393e+07,AU
110,The Ten Commandments,12/12/1958,78.0,"Drama, History","Escaping death, a Hebrew infant is raised in a...","Charlton Heston, Moses, Yul Brynner, Rameses, ...",The Ten Commandments,Released,English,10000000.0,1.051907e+06,AU
169,The Lost City,03/30/2022,66.0,"Action, Adventure, Comedy",Reclusive author Loretta Sage writes about exo...,"Sandra Bullock, Loretta Sage / Angela, Channin...",The Lost City,Released,English,74000000.0,1.829220e+08,AU
...,...,...,...,...,...,...,...,...,...,...,...,...
9543,Pinocchio,10/11/2002,58.0,"Comedy, Family, Fantasy",Roberto Benigni adapts the classic children's ...,"Roberto Benigni, Pinocchio, Nicoletta Braschi,...",Pinocchio,Released,Italian,45000000.0,3.168181e+07,IT
9544,Pinocchio,10/11/2002,58.0,"Comedy, Family, Fantasy",Roberto Benigni adapts the classic children's ...,"Roberto Benigni, Pinocchio, Nicoletta Braschi,...",Pinocchio,Released,Italian,13200000.0,3.036038e+07,IT
9545,Pinocchio,10/11/2002,58.0,"Comedy, Family, Fantasy",Roberto Benigni adapts the classic children's ...,"Roberto Benigni, Pinocchio, Nicoletta Braschi,...",Pinocchio,Released,Italian,2289247.0,8.430000e+07,IT
9642,Alice in Wonderland,08/13/1999,63.0,"Fantasy, Family",Alice follows a white rabbit down a rabbit-hol...,"Tina Majorino, Alice, Robbie Coltrane, Tweedle...",Alice in Wonderland,Released,English,200000000.0,1.025491e+09,AU
9643,Alice in Wonderland,08/13/1999,63.0,"Fantasy, Family",Alice follows a white rabbit down a rabbit-hol...,"Tina Majorino, Alice, Robbie Coltrane, Tweedle...",Alice in Wonderland,Released,English,3000000.0,0.000000e+00,AU

In [64]:
# eliminazione di tutti i duplicati
indice_duplicati = doppioni.index
imdb_movies_clean = imdb_movies_clean.drop(indice_duplicati)
imdb_movies_clean.shape
# 10,178 righe originali - 347 righe dei doppioni = 9831 righe finali

(9831, 12)

#### Verifico se esistono ancora degli omonimi, e che abbiano dei valori diversi pur avendo lo stesso titolo

In [65]:
omonimi = imdb_movies_clean['names'].value_counts()
omonimi = omonimi[omonimi > 1]
omonimi

names
Porno                      5
Jesus                      4
Prey                       4
Lady Chatterley's Lover    3
The Girl Next Door         3
                          ..
The Time Machine           2
Freaky Friday              2
The Hills Have Eyes        2
Ava                        2
Doctor Dolittle            2
Name: count, Length: 235, dtype: int64

In [66]:
imdb_movies_clean[imdb_movies_clean['names'] == 'Jesus']

,names,date_x,score,genre,overview,crew,orig_title,status,orig_lang,budget_x,revenue,country
204,Jesus,10/19/1979,83.0,"Drama, History","Three and a half years of Jesus' ministry, as ...","Brian Deacon, Jesus, Rivka Neuman, Mary, Alexa...",Jesus,Released,English,179800000.0,600820848.4,US
902,Jesus,12/05/1999,63.0,"History, Drama",The film is notable for presenting a more huma...,"Jeremy Sisto, Jesus, Debra Messing, Maria Mada...",Jesus,Released,English,20000000.0,192810486.8,US
8303,Jesus,01/01/1999,0.0,History,We don't have an overview translated in Englis...,"Simone Catalucci, Jesus, alessandro carbonell,...",Jesus,Released,Italian,213940000.0,175269998.8,IT
9011,Jesus,09/19/2016,60.0,Drama,"18-year-old Jesús lives with his stern, somewh...","Nicolás Durán, Jesús, Alejandro Goic, Héctor, ...",Jesús,Released,"Spanish, Castilian",73800000.0,346352260.6,ES

#### Ora possiamo passare alla prossima fase di pulizia: tenere solo le colonne interessanti e rinominarle

In [67]:
# sistemazione colonne
imdb_movies_clean = imdb_movies_clean.drop(['status'], axis=1)
imdb_movies_clean = imdb_movies_clean.rename(columns={'names':'movie_title','date_x':'release_date','score':'imdb_score'})
imdb_movies_clean.head(1)

,movie_title,release_date,imdb_score,genre,overview,crew,orig_title,orig_lang,budget_x,revenue,country
0,Creed III,03/02/2023,73.0,"Drama, Action","After dominating the boxing world, Adonis Cree...","Michael B. Jordan, Adonis Creed, Tessa Thompso...",Creed III,English,75000000.0,271616668.0,AU

In [68]:
imdb_movies_clean['release_year'] = pd.to_datetime(imdb_movies_clean['release_date']).dt.year # estraiamo l'anno di uscita

In [69]:
imdb_movies_clean.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9831 entries, 0 to 10177
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   movie_title   9831 non-null   object
 1   release_date  9831 non-null   object
 2   imdb_score    9831 non-null   float64
 3   genre         9746 non-null   object
 4   overview      9831 non-null   object
 5   crew          9775 non-null   object
 6   orig_title    9831 non-null   object
 7   orig_lang     9831 non-null   object
 8   budget_x      9831 non-null   float64
 9   revenue       9831 non-null   float64
 10  country       9831 non-null   object
 11  release_year  9831 non-null   int32
dtypes: float64(3), int32(1), object(8)
memory usage: 960.1+ KB

In [70]:
#salviamo il csv
imdb_movies_clean.to_csv("C:\\Users\\loren\\Desktop\\Final Project\\imdb_movies_clean", index=False)

## Importo il secondo dataframe

link alla pagina: https://www.kaggle.com/datasets/carolzhangdc/imdb-5000-movie-dataset

#### Questo secondo df ha i dati di regista, cast, durata, numero di votazioni su imdb, popolarità (numero di like su facebook)

In [71]:
imdb5000 = pd.read_csv("C:\\Users\\loren\\Desktop\\Final Project\\imdb_5000.csv")

In [72]:
imdb5000

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,...,3054.0,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,...,1238.0,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0
2,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,...,994.0,English,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000
3,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,...,2701.0,English,USA,PG-13,250000000.0,2012.0,23000.0,8.5,2.35,164000
4,NaN,Doug Walker,NaN,NaN,131.0,NaN,Rob Walker,131.0,NaN,Documentary,...,NaN,NaN,NaN,NaN,NaN,NaN,12.0,7.1,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5038,Color,Scott Smith,1.0,87.0,2.0,318.0,Daphne Zuniga,637.0,NaN,Comedy|Drama,...,6.0,English,Canada,NaN,NaN,2013.0,470.0,7.7,NaN,84
5039,Color,NaN,43.0,43.0,NaN,319.0,Valorie Curry,841.0,NaN,Crime|Drama|Mystery|Thriller,...,359.0,English,USA,TV-14,NaN,NaN,593.0,7.5,16.00,32000
5040,Color,Benjamin Roberds,13.0,76.0,0.0,0.0,Maxwell Moody,0.0,NaN,Drama|Horror|Thriller,...,3.0,English,USA,NaN,1400.0,2013.0,0.0,6.3,NaN,16
5041,Color,Daniel Hsia,14.0,100.0,0.0,489.0,Daniel Henney,946.0,10443.0,Comedy|Drama|Romance,...,9.0,English,USA,PG-13,NaN,2012.0,719.0,6.3,2.35,660
5042,Color,Jon Gunn,43.0,90.0,16.0,16.0,Brian Herzlinger,86.0,85222.0,Documentary,...,84.0,English,USA,PG,1100.0,2004.0,23.0,6.6,1.85,456

In [73]:
imdb5000.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5043 entries, 0 to 5042
Data columns (total 28 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   color                      5024 non-null   object
 1   director_name              4939 non-null   object
 2   num_critic_for_reviews     4993 non-null   float64
 3   duration                   5028 non-null   float64
 4   director_facebook_likes    4939 non-null   float64
 5   actor_3_facebook_likes     5020 non-null   float64
 6   actor_2_name               5030 non-null   object
 7   actor_1_facebook_likes     5036 non-null   float64
 8   gross                      4159 non-null   float64
 9   genres                     5043 non-null   object
 10  actor_1_name               5036 non-null   object
 11  movie_title                5043 non-null   object
 12  num_voted_users            5043 non-null   int64
 13  cast_total_facebook_likes  5043 non-null   int64
 14  actor_3_name               5020 non-null   object
 15  facenumber_in_poster       5030 non-null   float64
 16  plot_keywords              4890 non-null   object
 17  movie_imdb_link            5043 non-null   object
 18  num_user_for_reviews       5022 non-null   float64
 19  language                   5029 non-null   object
 20  country                    5038 non-null   object
 21  content_rating             4740 non-null   object
 22  budget                     4551 non-null   float64
 23  title_year                 4935 non-null   float64
 24  actor_2_facebook_likes     5030 non-null   float64
 25  imdb_score                 5043 non-null   float64
 26  aspect_ratio               4714 non-null   float64
 27  movie_facebook_likes       5043 non-null   int64
dtypes: float64(13), int64(3), object(12)
memory usage: 1.1+ MB

In [74]:
imdb5000_clean = imdb5000.copy()

#### Di questo df terremo solo `movie_title` `title_year` `duration` `color` `actor_1_name` `actor_2_name` `actor_3_name` `num_critic_for_reviews` `movie_facebook_likes` `director_name` `director_facebook_likes` `cast_total_facebook_likes` `language`

In [75]:
imdb5000_clean = imdb5000_clean.loc[:,['movie_title','title_year','duration', 'color',
                                       'director_name','actor_1_name','actor_2_name','actor_3_name',
                                       'num_critic_for_reviews','movie_facebook_likes','director_facebook_likes','cast_total_facebook_likes']]

In [76]:
imdb5000_clean.head(3)

,movie_title,title_year,duration,color,director_name,actor_1_name,actor_2_name,actor_3_name,num_critic_for_reviews,movie_facebook_likes,director_facebook_likes,cast_total_facebook_likes
0,Avatar,2009.0,178.0,Color,James Cameron,CCH Pounder,Joel David Moore,Wes Studi,723.0,33000,0.0,4834
1,Pirates of the Caribbean: At World's End,2007.0,169.0,Color,Gore Verbinski,Johnny Depp,Orlando Bloom,Jack Davenport,302.0,0,563.0,48350
2,Spectre,2015.0,148.0,Color,Sam Mendes,Christoph Waltz,Rory Kinnear,Stephanie Sigman,602.0,85000,0.0,11700

In [77]:
imdb5000_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5043 entries, 0 to 5042
Data columns (total 12 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   movie_title                5043 non-null   object
 1   title_year                 4935 non-null   float64
 2   duration                   5028 non-null   float64
 3   color                      5024 non-null   object
 4   director_name              4939 non-null   object
 5   actor_1_name               5036 non-null   object
 6   actor_2_name               5030 non-null   object
 7   actor_3_name               5020 non-null   object
 8   num_critic_for_reviews     4993 non-null   float64
 9   movie_facebook_likes       5043 non-null   int64
 10  director_facebook_likes    4939 non-null   float64
 11  cast_total_facebook_likes  5043 non-null   int64
dtypes: float64(4), int64(2), object(6)
memory usage: 472.9+ KB

#### Controllo duplicati

In [78]:
# controlliamo i duplicati di nome & anno di uscita & nome regista
doppioni = imdb5000_clean[imdb5000_clean.duplicated(subset=['movie_title','title_year','director_name'], keep=False)]
doppioni.sort_values('movie_title')

,movie_title,title_year,duration,color,director_name,actor_1_name,actor_2_name,actor_3_name,num_critic_for_reviews,movie_facebook_likes,director_facebook_likes,cast_total_facebook_likes
3711,"20,000 Leagues Under the Sea",1954.0,127.0,Color,Richard Fleischer,James Mason,Robert J. Wilke,Paul Lukas,69.0,0,130.0,799
4894,"20,000 Leagues Under the Sea",1954.0,127.0,Color,Richard Fleischer,James Mason,Robert J. Wilke,Paul Lukas,69.0,0,130.0,800
4950,A Dog's Breakfast,2007.0,88.0,Color,David Hewlett,Christopher Judge,David Hewlett,Paul McGillion,8.0,377,686.0,2364
4949,A Dog's Breakfast,2007.0,88.0,Color,David Hewlett,Christopher Judge,David Hewlett,Paul McGillion,8.0,377,686.0,2364
1420,A Nightmare on Elm Street,1984.0,101.0,Color,Wes Craven,Johnny Depp,Lin Shaye,Amanda Wyss,256.0,10000,0.0,42918
...,...,...,...,...,...,...,...,...,...,...,...,...
1305,Victor Frankenstein,2015.0,110.0,Color,Paul McGuigan,Daniel Radcliffe,Spencer Wilding,Daniel Mays,159.0,11000,118.0,12876
1146,Victor Frankenstein,2015.0,110.0,Color,Paul McGuigan,Daniel Radcliffe,Spencer Wilding,Daniel Mays,159.0,11000,118.0,12876
2099,Victor Frankenstein,2015.0,110.0,Color,Paul McGuigan,Daniel Radcliffe,Spencer Wilding,Daniel Mays,159.0,11000,118.0,12876
2169,Wicker Park,2004.0,114.0,Color,Paul McGuigan,Jessica Paré,Christopher Cousins,Mark Camacho,98.0,0,118.0,679
1697,Wicker Park,2004.0,114.0,Color,Paul McGuigan,Jessica Paré,Christopher Cousins,Mark Camacho,98.0,0,118.0,679

Avendo controllato per 3 colonne, possiamo essere sicuri che questi siano duplicati, dunque li eliminiamo tenendo solo il primo

In [79]:
imdb5000_clean = imdb5000_clean.drop_duplicates(subset = ['movie_title','title_year','director_name'], keep = 'first')

#### Droppiamo i film senza anno di uscita

In [80]:
no_anno = imdb5000_clean.loc[imdb5000_clean['title_year'].isna()].index
imdb5000_clean = imdb5000_clean.drop(index=no_anno)

In [81]:
imdb5000_clean.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4813 entries, 0 to 5042
Data columns (total 12 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   movie_title                4813 non-null   object
 1   title_year                 4813 non-null   float64
 2   duration                   4801 non-null   float64
 3   color                      4798 non-null   object
 4   director_name              4813 non-null   object
 5   actor_1_name               4806 non-null   object
 6   actor_2_name               4803 non-null   object
 7   actor_3_name               4795 non-null   object
 8   num_critic_for_reviews     4773 non-null   float64
 9   movie_facebook_likes       4813 non-null   int64
 10  director_facebook_likes    4813 non-null   float64
 11  cast_total_facebook_likes  4813 non-null   int64
dtypes: float64(4), int64(2), object(6)
memory usage: 488.8+ KB

In [82]:
# salviamo il csv
imdb5000_clean.to_csv("C:\\Users\\loren\\Desktop\\Final Project\\imdb_5000_clean.csv", index=False)

## Merge

#### Uniamo i dati del secondo df a quelli del primo, facendo una merge su due chiavi: titolo e anno di uscita

Facciamo anzitutto una normalizzazione delle colonne titolo: tutto in minuscolo e rimozione di spazi vuoti e caratteri

In [83]:
imdb_movies_clean['movie_title'] = imdb_movies_clean['movie_title'].str.strip().str.lower() # normalizzazione del titolo
imdb5000_clean['movie_title'] = imdb5000_clean['movie_title'].str.strip().str.lower()       # per entrambi i df

In [84]:
df_movies_merged = pd.merge(
    imdb_movies_clean,                      # df da 10k righe
    imdb5000_clean,                         # df secondario
    left_on=['movie_title','release_year'], # doppia chiave per evitare gli omonimi
    right_on=['movie_title','title_year'],
    how='inner'                             # inner join per tenere solo le righe con tutti i dati      
)

In [85]:
df_movies_merged

,movie_title,release_date,imdb_score,genre,overview,crew,orig_title,orig_lang,budget_x,revenue,...,duration,color,director_name,actor_1_name,actor_2_name,actor_3_name,num_critic_for_reviews,movie_facebook_likes,director_facebook_likes,cast_total_facebook_likes
0,the passion of the christ,02/25/2004,74.0,Drama,A graphic portrayal of the last twelve hours o...,"Jim Caviezel, Jesus, Maia Morgenstern, Maria, ...",The Passion of the Christ,English,25000000.0,6.223136e+08,...,120.0,Color,Mel Gibson,Christo Jivkov,Maia Morgenstern,Hristo Shopov,406.0,13000,0.0,705
1,avatar,12/17/2009,76.0,"Action, Adventure, Fantasy, Science Fiction","In the 22nd century, a paraplegic Marine is di...","Sam Worthington, Jake Sully, Zoe Saldaña, Neyt...",Avatar,English,237000000.0,2.923706e+09,...,178.0,Color,James Cameron,CCH Pounder,Joel David Moore,Wes Studi,723.0,33000,0.0,4834
2,super mario bros.,06/10/1993,43.0,"Action, Adventure, Comedy, Family, Science Fic...","Mario and Luigi, plumbers from Brooklyn, find ...","Bob Hoskins, Mario Mario, John Leguizamo, Luig...",Super Mario Bros.,English,42000000.0,2.084491e+07,...,104.0,Color,Annabel Jankel,Bob Hoskins,Fisher Stevens,Fiona Shaw,36.0,0,5.0,7723
3,creed,11/26/2015,74.0,Drama,The former World Heavyweight Champion Rocky Ba...,"Michael B. Jordan, Adonis Johnson, Sylvester S...",Creed,English,37000000.0,1.735676e+08,...,133.0,Color,Ryan Coogler,Sylvester Stallone,Phylicia Rashad,Graham McTavish,437.0,70000,0.0,15106
4,"the chronicles of narnia: the lion, the witch ...",12/26/2005,71.0,"Adventure, Family, Fantasy","Siblings Lucy, Edmund, Susan and Peter step th...","Georgie Henley, Lucy Pevensie, Skandar Keynes,...","The Chronicles of Narnia: The Lion, the Witch ...",English,180000000.0,7.450131e+08,...,150.0,Color,Andrew Adamson,Jim Broadbent,Kiran Shah,Shane Rangi,284.0,0,80.0,1317
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1970,hustle & flow,07/22/2005,71.0,"Crime, Drama, Music","With help from his friends, a Memphis pimp in ...","Terrence Howard, Djay, Anthony Anderson, Key, ...",Hustle & Flow,English,2800000.0,2.359178e+07,...,116.0,Color,Craig Brewer,Isaac Hayes,Paula Jai Parker,Elise Neal,159.0,0,153.0,727
1971,hardball,09/14/2001,64.0,Drama,"An aimless young man who is scalping tickets, ...","Keanu Reeves, Conor O'Neill, Diane Lane, Eliza...",Hardball,English,21000000.0,4.372856e+07,...,106.0,Color,Brian Robbins,Keanu Reeves,D.B. Sweeney,DeWayne Warren,85.0,0,48.0,18630
1972,heaven's gate,11/19/1980,68.0,"Drama, Western",Harvard graduate James Averill is the sheriff ...,"Kris Kristofferson, James Averill, Christopher...",Heaven's Gate,English,44000000.0,3.484523e+06,...,325.0,Color,Michael Cimino,Jeff Bridges,Sam Waterston,Isabelle Huppert,102.0,1000,517.0,14255
1973,nighthawks,04/04/1981,64.0,"Action, Crime, Thriller",An international terrorist has New York in a g...,"Sylvester Stallone, Det. Sgt. Deke DaSilva, Ru...",Nighthawks,English,5000000.0,1.960000e+07,...,99.0,Color,Bruce Malmuth,Sylvester Stallone,Lindsay Wagner,Persis Khambatta,36.0,0,6.0,14306
1974,the love guru,07/10/2008,42.0,"Comedy, Romance",Born in America and raised in an Indian ashram...,"Mike Myers, Guru Pitka, Jessica Alba, Jane Bul...",The Love Guru,English,62000000.0,4.015902e+07,...,87.0,Color,Marco Schnabel,Justin Timberlake,Romany Malco,Verne Troyer,150.0,0,12.0,6658

## Pulizia finale

In [86]:
df_movies_merged.head(1)

,movie_title,release_date,imdb_score,genre,overview,crew,orig_title,orig_lang,budget_x,revenue,...,duration,color,director_name,actor_1_name,actor_2_name,actor_3_name,num_critic_for_reviews,movie_facebook_likes,director_facebook_likes,cast_total_facebook_likes
0,the passion of the christ,02/25/2004,74.0,Drama,A graphic portrayal of the last twelve hours o...,"Jim Caviezel, Jesus, Maia Morgenstern, Maria, ...",The Passion of the Christ,English,25000000.0,622313635.0,...,120.0,Color,Mel Gibson,Christo Jivkov,Maia Morgenstern,Hristo Shopov,406.0,13000,0.0,705

In [87]:
df_movies_merged.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1975 entries, 0 to 1974
Data columns (total 23 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   movie_title                1975 non-null   object
 1   release_date               1975 non-null   object
 2   imdb_score                 1975 non-null   float64
 3   genre                      1975 non-null   object
 4   overview                   1975 non-null   object
 5   crew                       1975 non-null   object
 6   orig_title                 1975 non-null   object
 7   orig_lang                  1975 non-null   object
 8   budget_x                   1975 non-null   float64
 9   revenue                    1975 non-null   float64
 10  country                    1975 non-null   object
 11  release_year               1975 non-null   int32
 12  title_year                 1975 non-null   float64
 13  duration                   1975 non-null   float64
 14  color                      1972 non-null   object
 15  director_name              1975 non-null   object
 16  actor_1_name               1975 non-null   object
 17  actor_2_name               1974 non-null   object
 18  actor_3_name               1974 non-null   object
 19  num_critic_for_reviews     1974 non-null   float64
 20  movie_facebook_likes       1975 non-null   int64
 21  director_facebook_likes    1975 non-null   float64
 22  cast_total_facebook_likes  1975 non-null   int64
dtypes: float64(7), int32(1), int64(2), object(13)
memory usage: 347.3+ KB

#### Gestione delle colonne

In [88]:
df_movies_merged = df_movies_merged.drop(['title_year','crew'], axis=1)

In [89]:
df_movies_merged = df_movies_merged.rename(columns={'duration':'duration[min]','budget_x':'budget', 'num_critic_for_reviews':'review_num'})
df_movies_merged.head(1)

,movie_title,release_date,imdb_score,genre,overview,orig_title,orig_lang,budget,revenue,country,...,duration[min],color,director_name,actor_1_name,actor_2_name,actor_3_name,review_num,movie_facebook_likes,director_facebook_likes,cast_total_facebook_likes
0,the passion of the christ,02/25/2004,74.0,Drama,A graphic portrayal of the last twelve hours o...,The Passion of the Christ,English,25000000.0,622313635.0,AU,...,120.0,Color,Mel Gibson,Christo Jivkov,Maia Morgenstern,Hristo Shopov,406.0,13000,0.0,705

#### Trasformazione dei valori float non necessari in int (`imdb_score`, `budget`, `revenue`, `duration`, `review_num`, `director_facebook_likes`)

In [90]:
colonne = ['imdb_score','budget','revenue','duration[min]','review_num','director_facebook_likes']
df_movies_merged[colonne] = df_movies_merged[colonne].round(0).astype('Int64') # arrotondo e poi cambio type

#### Creazione della colonna `cast` unendo i 3 attori/attrici principali

Al momento la colonna del cast è divisa in 3 colonne diverse, uniamole in una unica che chiameremo `cast`

In [91]:
df_movies_merged['cast'] = df_movies_merged['actor_1_name'] + ', ' + df_movies_merged['actor_2_name'] + ', ' + df_movies_merged['actor_3_name']

Cancelliamo le colonne divise

In [92]:
df_movies_merged = df_movies_merged.drop(['actor_1_name','actor_2_name','actor_3_name'], axis=1)

In [93]:
df_movies_merged.head(1)

,movie_title,release_date,imdb_score,genre,overview,orig_title,orig_lang,budget,revenue,country,release_year,duration[min],color,director_name,review_num,movie_facebook_likes,director_facebook_likes,cast_total_facebook_likes,cast
0,the passion of the christ,02/25/2004,74,Drama,A graphic portrayal of the last twelve hours o...,The Passion of the Christ,English,25000000,622313635,AU,2004,120,Color,Mel Gibson,406,13000,0,705,"Christo Jivkov, Maia Morgenstern, Hristo Shopov"

#### Controllo qualità sulle colonne

In [94]:
len(df_movies_merged.loc[df_movies_merged['imdb_score'] == 0])

0

In [95]:
len(df_movies_merged.loc[df_movies_merged['budget'] == 0])

0

In [96]:
len(df_movies_merged.loc[df_movies_merged['revenue'] == 0])

11

In [97]:
df_movies_merged.loc[df_movies_merged['revenue'] == 0]

,movie_title,release_date,imdb_score,genre,overview,orig_title,orig_lang,budget,revenue,country,release_year,duration[min],color,director_name,review_num,movie_facebook_likes,director_facebook_likes,cast_total_facebook_likes,cast
591,never back down 2: the beatdown,09/13/2011,65,"Drama, Action",Four fighters from different backgrounds come ...,Never Back Down 2: The Beatdown,English,3000000,0,US,2011,90,Color,Michael Jai White,23,6000,2000,3666,"Michael Jai White, Alex Meraz, Jillian Murray"
618,"batman: the dark knight returns, part 2",01/03/2013,80,"Science Fiction, Action, Animation, Mystery",Batman has stopped the reign of terror that Th...,"Batman: The Dark Knight Returns, Part 2",English,3500000,0,AU,2013,148,Color,Jay Oliva,44,5000,41,5526,"Michael Emerson, Mark Valley, Grey Griffin"
704,high school musical 2,08/17/2007,65,"Comedy, Drama, Family, Music, Romance, TV Movie",The East High Wildcats are gearing up for big ...,High School Musical 2,English,7000000,0,US,2007,111,Color,Kenny Ortega,44,586,197,3009,"Lucas Grabeel, Corbin Bleu, Olesya Rulin"
726,the ridiculous 6,12/11/2015,52,"Western, Comedy","When his long-lost outlaw father returns, Tomm...",The Ridiculous 6,English,60000000,0,US,2015,119,Color,Frank Coraci,53,0,153,36167,"Taylor Lautner, Adam Sandler, Jon Lovitz"
1008,independence daysaster,06/27/2013,46,"Action, Science Fiction",When Earth is attacked by a hostile alien forc...,Independence Daysaster,English,1800000,0,US,2013,90,Color,W.D. Hogan,10,566,4,984,"Tom Everett Scott, Keenan Tracey, Nicholas Car..."
1054,barbarella,10/17/1968,60,"Science Fiction, Adventure","In the far future, a highly sexual woman is ta...",Barbarella,English,9000000,0,AU,1968,98,Color,Roger Vadim,107,0,35,1510,"Jane Fonda, David Hemmings, Milo O'Shea"
1058,dead like me: life after death,06/03/2009,63,"Drama, Fantasy, Comedy",When George and her colleagues get a new boss ...,Dead Like Me: Life After Death,English,5000000,0,AU,2009,87,Color,Stephen Herek,19,887,65,3724,"Henry Ian Cusick, Callum Blue, Shenae Grimes-B..."
1256,the prince,08/22/2014,49,"Thriller, Action",A family man who turns out to be a retired mob...,The Prince,English,18000000,0,US,2014,93,Color,Brian A Miller,46,0,32,16735,"Bruce Willis, 50 Cent, Jessica Lowndes"
1499,pound of flesh,05/07/2015,58,Action,In China to donate his kidney to his dying nie...,Pound of Flesh,English,7500000,0,US,2015,104,Color,Ernie Barbarash,36,0,249,835,"Darren Shahlavi, Aki Aleong, Brahim Achabbakhe"
1798,silent running,03/09/1972,64,"Adventure, Science Fiction",In a future Earth barren of all flora and faun...,Silent Running,English,1100000,0,AU,1972,89,Color,Douglas Trumbull,87,0,136,1080,"Bruce Dern, Ron Rifkin, Jesse Vint"
1924,death race 2000,04/30/1975,61,"Action, Comedy, Science Fiction","In a boorish future, the government sponsors a...",Death Race 2000,English,300000,0,US,1975,80,Color,Paul Bartel,164,0,43,14950,"Sylvester Stallone, David Carradine, Martin Kove"

In [98]:
len(df_movies_merged.loc[df_movies_merged['duration[min]'] == 0])

0

In [99]:
len(df_movies_merged.loc[df_movies_merged['movie_facebook_likes'] == 0]) # !!!

978

In [100]:
len(df_movies_merged.loc[df_movies_merged['director_facebook_likes'] == 0]) # !!

306

In [101]:
len(df_movies_merged.loc[df_movies_merged['cast_total_facebook_likes'] == 0])

1

In [102]:
df_movies_merged.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1975 entries, 0 to 1974
Data columns (total 19 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   movie_title                1975 non-null   object
 1   release_date               1975 non-null   object
 2   imdb_score                 1975 non-null   Int64
 3   genre                      1975 non-null   object
 4   overview                   1975 non-null   object
 5   orig_title                 1975 non-null   object
 6   orig_lang                  1975 non-null   object
 7   budget                     1975 non-null   Int64
 8   revenue                    1975 non-null   Int64
 9   country                    1975 non-null   object
 10  release_year               1975 non-null   int32
 11  duration[min]              1975 non-null   Int64
 12  color                      1972 non-null   object
 13  director_name              1975 non-null   object
 14  review_num                 1974 non-null   Int64
 15  movie_facebook_likes       1975 non-null   int64
 16  director_facebook_likes    1975 non-null   Int64
 17  cast_total_facebook_likes  1975 non-null   int64
 18  cast                       1974 non-null   object
dtypes: Int64(6), int32(1), int64(2), object(10)
memory usage: 297.2+ KB

#### Esportazione in csv

In [103]:
df_movies_merged.to_csv("C:\\Users\\loren\\Desktop\\Final Project\\df_film_analisi.csv", index=False)

In [104]:
df_movies_merged.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1975 entries, 0 to 1974
Data columns (total 19 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   movie_title                1975 non-null   object
 1   release_date               1975 non-null   object
 2   imdb_score                 1975 non-null   Int64
 3   genre                      1975 non-null   object
 4   overview                   1975 non-null   object
 5   orig_title                 1975 non-null   object
 6   orig_lang                  1975 non-null   object
 7   budget                     1975 non-null   Int64
 8   revenue                    1975 non-null   Int64
 9   country                    1975 non-null   object
 10  release_year               1975 non-null   int32
 11  duration[min]              1975 non-null   Int64
 12  color                      1972 non-null   object
 13  director_name              1975 non-null   object
 14  review_num                 1974 non-null   Int64
 15  movie_facebook_likes       1975 non-null   int64
 16  director_facebook_likes    1975 non-null   Int64
 17  cast_total_facebook_likes  1975 non-null   int64
 18  cast                       1974 non-null   object
dtypes: Int64(6), int32(1), int64(2), object(10)
memory usage: 297.2+ KB